//LOOPS EXECUTES THE BLOCK OF CODE REPEATEDLY

//FOR LOOP

//IT FOLLOWS INITIALISATION ,TEST CONDITION ,INCREMENT OR DECREMENT
//IT IS USED EXECUTE THE FOLLOWING CODE UNTIL IT GOES FALSE

let a=5;
for(let b=1;b<a;b++){
    console.log(b);
    
}