//THEY ARE CONTAINER TO STORE VALUES

//3 TYPES

//VAR

// IT IS AN OLDER VERSION
// IT CAN BE REDECLARED AND REASSINGNED
// IT CAN BE USED OUTSIDE THE BLOCK -GLOBAL

var a=5;
var b=10;
console.log(a,b);

//LET

//IT IS THE NEW VERSION 
//IT CAN BE REDECLARED BUT CANNOT BE REAASIGNED
//IT IS DECLARED WITHIN THE BLOCK

let c=6;
 c=7;
console.log(c);

//CONST

//IT IS AN UNIQUE VALUE
//IT IS A NEWER VERSION
//IT CAN BE DECLARED WITHIN THE BLOCK

const e=8464738929;
console.log(e);
